trigger:
  - main

pool:
  name: Default
  demands:
    - agent.name -equals Linux-Mint

steps:
  - task: NodeTool@1
    inputs:
      versionSpec: '22.x'
    displayName: 'Use Node.js 22'

  - script: |
      npm ci
    displayName: Install dependencies

  # Playwright browsers are not included in the npm ci step, so we need to install them separately. The --with-deps flag ensures that all necessary dependencies are installed as well.
  #However, since the Self-Hosted agent requires sudo permissions to install the browsers, we will skip this step and assume that the browsers are already installed on the agent.
  #- script: npx playwright install --with-deps
  #  displayName: Install Playwright browsers

  - script: npx playwright test
    displayName: Run Playwright tests

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: test-results/*.xml

  - task: PublishPipelineArtifact@1
    condition: always()
    inputs:
      targetPath: playwright-report
      artifact: playwright-report