trigger:
  - main

pool:
  name: Default
  demands:
    - agent.name -equals Linux-Mint

steps:
  - task: NodeTool@1
    inputs:
      versionSpec: '22.x'

  - script: |
      echo "Node path:"
      which node

      echo "NPM path:"
      which npm

      echo "Node version:"
      node -v

      echo "NPM version:"
      npm -v

      echo "NPM config:"
      npm config list

      echo "Install dependencies:"
      npm ci --verbose
    displayName: Check Node, NPM and install dependencies

  - script: |
      pwd
      ls -la
      npm ci
    displayName: Install dependencies

  - script: npx playwright install --with-deps
    displayName: Install Playwright browsers

  - script: npx playwright test
    displayName: Run Playwright tests

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: test-results/*.xml

  - task: PublishPipelineArtifact@1
    condition: always()
    inputs:
      targetPath: playwright-report
      artifact: playwright-report